version: '3.4'

services:
  sql1:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "<Gisw5/WugjXicu>"
      ACCEPT_EULA: "Y"
    networks:
      rtm-net:
        ipv4_address: 10.0.0.2
  radontestsmanager:
    image: "${DOCKER_REGISTRY-}radontestsmanager"
    build:
      context: "."
      dockerfile: "RadonTestsManager/Dockerfile"
    ports: 
      - "5000:80"
    networks:
      rtm-net:
        ipv4_address: 10.0.0.3
    depends_on:
      - sql1
networks:
  rtm-net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16