// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadonTestsManager.DBContext;

namespace RadonTestsManager.Migrations
{
    [DbContext(typeof(RadonTestsManagerContext))]
    [Migration("20190108120819_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RadonTestsManager.CRMs.Models.ContinuousRadonMonitor", b =>
                {
                    b.Property<int>("CRMId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastBatteryChangeDate");

                    b.Property<DateTime>("LastCalibrationDate");

                    b.Property<int?>("LocationAddressId");

                    b.Property<int>("MonitorNumber");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<int>("SerialNumber");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TestFinish");

                    b.Property<DateTime>("TestStart");

                    b.HasKey("CRMId");

                    b.HasIndex("LocationAddressId");

                    b.ToTable("ContinuousRadonMonitors");
                });

            modelBuilder.Entity("RadonTestsManager.CRMs.Models.CRMMaintenanceLogEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CRMId1");

                    b.HasKey("EntryId");

                    b.HasIndex("CRMId1");

                    b.ToTable("CRMMaintenanceLogEntry");
                });

            modelBuilder.Entity("RadonTestsManager.Jobs.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessInfo");

                    b.Property<DateTime>("ArrivalTime");

                    b.Property<int?>("ContinousRadonMonitorCRMId");

                    b.Property<string>("DeviceType");

                    b.Property<string>("Driver");

                    b.Property<int?>("JobAddressAddressId");

                    b.Property<int?>("LSVialId");

                    b.Property<DateTime>("ServiceDeadLine");

                    b.Property<string>("ServiceType");

                    b.Property<string>("SpecialNotes");

                    b.HasKey("JobId");

                    b.HasIndex("ContinousRadonMonitorCRMId");

                    b.HasIndex("JobAddressAddressId");

                    b.HasIndex("LSVialId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("RadonTestsManager.LSVials.Models.LSVial", b =>
                {
                    b.Property<int>("LSVialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SerialNumber");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TestFinish");

                    b.Property<DateTime>("TestStart");

                    b.HasKey("LSVialId");

                    b.ToTable("LSVials");
                });

            modelBuilder.Entity("RadonTestsManager.Model.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("CustomerName");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("RadonTestsManager.CRMs.Models.ContinuousRadonMonitor", b =>
                {
                    b.HasOne("RadonTestsManager.Model.Address", "Location")
                        .WithMany()
                        .HasForeignKey("LocationAddressId");
                });

            modelBuilder.Entity("RadonTestsManager.CRMs.Models.CRMMaintenanceLogEntry", b =>
                {
                    b.HasOne("RadonTestsManager.CRMs.Models.ContinuousRadonMonitor", "CRMId")
                        .WithMany("MaintenanceLog")
                        .HasForeignKey("CRMId1");
                });

            modelBuilder.Entity("RadonTestsManager.Jobs.Models.Job", b =>
                {
                    b.HasOne("RadonTestsManager.CRMs.Models.ContinuousRadonMonitor", "ContinousRadonMonitor")
                        .WithMany("JobHistory")
                        .HasForeignKey("ContinousRadonMonitorCRMId");

                    b.HasOne("RadonTestsManager.Model.Address", "JobAddress")
                        .WithMany("JobHistory")
                        .HasForeignKey("JobAddressAddressId");

                    b.HasOne("RadonTestsManager.LSVials.Models.LSVial", "LSvial")
                        .WithMany("JobHistory")
                        .HasForeignKey("LSVialId");
                });
#pragma warning restore 612, 618
        }
    }
}
